import type { Badge, DailyTask, FlashcardSession, WeaknessQuest } from "@/lib/types";

export const mockDailyTasks: DailyTask[] = [
  {
    id: "dt_001",
    title: "Vocabulary Revision",
    description: "Review 15 words from your weak bank",
    skill: "VOCABULARY",
    xpReward: 30,
    status: "DONE",
    estimatedMinutes: 8,
    icon: "Library",
  },
  {
    id: "dt_002",
    title: "Listening Trap Drill",
    description: "5 negation and contrast marker questions",
    skill: "LISTENING",
    xpReward: 50,
    status: "PENDING",
    estimatedMinutes: 12,
    icon: "Headphones",
  },
  {
    id: "dt_003",
    title: "Reading Passage",
    description: "Complete a B1+ reading comprehension",
    skill: "READING",
    xpReward: 40,
    status: "PENDING",
    estimatedMinutes: 15,
    icon: "BookOpen",
  },
  {
    id: "dt_004",
    title: "Speaking Prompt",
    description: "Record a 2-minute response on daily life",
    skill: "SPEAKING",
    xpReward: 60,
    status: "LOCKED",
    estimatedMinutes: 10,
    icon: "Mic",
  },
  {
    id: "dt_005",
    title: "Writing Task",
    description: "Write a formal email (150-200 words)",
    skill: "WRITING",
    xpReward: 70,
    status: "LOCKED",
    estimatedMinutes: 20,
    icon: "PenTool",
  },
];

export const mockWeaknessQuest: WeaknessQuest = {
  id: "wq_001",
  title: "Listening: Negation and Contrast Markers",
  description:
    "Your biggest weakness detected: you struggle with negation and contrast markers in listening exercises. Complete this quest to repair the gap.",
  skill: "LISTENING",
  trapType: "NEGATION",
  questionsCount: 10,
  xpReward: 150,
  difficulty: "HARD",
};

export const mockBadges: Badge[] = [
  {
    id: "badge_001",
    name: "Negation Hunter",
    description: "Master 50 negation-based listening traps",
    icon: "🎯",
    category: "LISTENING",
    earnedAt: "2026-04-20",
    progress: 100,
    requirement: "50 negation traps mastered",
    xpReward: 200,
  },
  {
    id: "badge_002",
    name: "Listening Survivor",
    description: "Complete 100 listening exercises without hints",
    icon: "🎧",
    category: "LISTENING",
    progress: 78,
    requirement: "100 exercises without hints",
    xpReward: 300,
  },
  {
    id: "badge_003",
    name: "B2 Writer",
    description: "Score B2 on 5 consecutive writing evaluations",
    icon: "✍️",
    category: "WRITING",
    progress: 40,
    requirement: "5 consecutive B2 writing scores",
    xpReward: 500,
  },
  {
    id: "badge_004",
    name: "Speaking Builder",
    description: "Record and submit 30 speaking responses",
    icon: "🗣️",
    category: "SPEAKING",
    progress: 63,
    requirement: "30 speaking responses submitted",
    xpReward: 300,
  },
  {
    id: "badge_005",
    name: "Mock Warrior",
    description: "Complete 5 full mock exams",
    icon: "⚔️",
    category: "MOCK_TEST",
    progress: 20,
    requirement: "5 full mock exams completed",
    xpReward: 500,
  },
  {
    id: "badge_006",
    name: "Connector Master",
    description: "Master all B2 French connectors and transitions",
    icon: "🔗",
    category: "VOCABULARY",
    earnedAt: "2026-04-28",
    progress: 100,
    requirement: "All B2 connectors mastered",
    xpReward: 250,
  },
  {
    id: "badge_007",
    name: "Speed Reader",
    description: "Read 20 passages under the time limit",
    icon: "📖",
    category: "READING",
    progress: 55,
    requirement: "20 passages under time limit",
    xpReward: 250,
  },
  {
    id: "badge_008",
    name: "Trap Killer",
    description: "Identify 100 exam trap questions correctly",
    icon: "💀",
    category: "MASTERY",
    progress: 34,
    requirement: "100 trap questions identified",
    xpReward: 400,
  },
  {
    id: "badge_009",
    name: "7-Day Warrior",
    description: "Maintain a 7-day practice streak",
    icon: "🔥",
    category: "STREAK",
    earnedAt: "2026-04-15",
    progress: 100,
    requirement: "7-day practice streak",
    xpReward: 100,
  },
  {
    id: "badge_010",
    name: "Vocab Beast",
    description: "Master 500 vocabulary words",
    icon: "📚",
    category: "VOCABULARY",
    progress: 48,
    requirement: "500 words mastered",
    xpReward: 400,
  },
  {
    id: "badge_011",
    name: "30-Day Legend",
    description: "Maintain a 30-day practice streak",
    icon: "👑",
    category: "STREAK",
    progress: 40,
    requirement: "30-day practice streak",
    xpReward: 500,
  },
  {
    id: "badge_012",
    name: "Diagnostic Ace",
    description: "Score above 70% on all diagnostic test sections",
    icon: "🏆",
    category: "MASTERY",
    progress: 50,
    requirement: "70%+ on all diagnostic sections",
    xpReward: 300,
  },
];

export const createEmptyFlashcardSession = (totalCards: number): FlashcardSession => ({
  deckType: "ALL",
  totalCards,
  reviewed: 0,
  mastered: 0,
  weakAdded: 0,
  xpEarned: 0,
  masteryImprovement: 0,
  reviews: [],
  startedAt: new Date("2026-05-04T00:00:00.000Z").toISOString(),
});
