import type { UserWordBankItem, VocabularyWord } from "@/lib/types";

export const mockVocabulary: VocabularyWord[] = [
  {
    id: "voc_001",
    frenchWord: "pourtant",
    englishMeaning: "however / yet",
    frenchExample: "Il voulait partir tôt, pourtant il est arrivé en retard.",
    englishExampleTranslation: "He wanted to leave early, yet he arrived late.",
    cefrLevel: "B1",
    topicType: "OPINION",
    examType: "ALL_EXAMS",
    frequencyScore: 95,
    tags: ["connector", "contrast", "trap-word"],
    trapType: "CONTRAST_MARKER",
    isPublished: true,
    status: "LEARNING",
    reviewCount: 4,
  },
  {
    id: "voc_002",
    frenchWord: "néanmoins",
    englishMeaning: "nevertheless / nonetheless",
    frenchExample: "Le projet est coûteux, néanmoins il est nécessaire.",
    englishExampleTranslation: "The project is costly, nevertheless it is necessary.",
    cefrLevel: "B2",
    topicType: "WORK",
    examType: "TEF_CANADA",
    frequencyScore: 88,
    tags: ["connector", "formal"],
    isPublished: true,
    status: "NEW",
    reviewCount: 0,
  },
  {
    id: "voc_003",
    frenchWord: "actuellement",
    englishMeaning: "currently / at present",
    frenchExample: "Actuellement, je travaille dans une entreprise de technologie.",
    englishExampleTranslation: "Currently, I work in a technology company.",
    cefrLevel: "B1",
    topicType: "WORK",
    examType: "ALL_EXAMS",
    frequencyScore: 92,
    tags: ["false-friend", "trap-word"],
    trapType: "FALSE_FRIEND",
    isPublished: true,
    status: "MASTERED",
    reviewCount: 12,
    lastReviewedAt: "2026-05-03",
  },
  {
    id: "voc_004",
    frenchWord: "en revanche",
    englishMeaning: "on the other hand",
    frenchExample: "Le prix est élevé. En revanche, la qualité est excellente.",
    englishExampleTranslation: "The price is high. On the other hand, the quality is excellent.",
    cefrLevel: "B2",
    topicType: "OPINION",
    examType: "ALL_EXAMS",
    frequencyScore: 85,
    tags: ["connector", "contrast"],
    trapType: "CONTRAST_MARKER",
    isPublished: true,
    status: "LEARNING",
    reviewCount: 3,
  },
  {
    id: "voc_005",
    frenchWord: "démarche",
    englishMeaning: "process / procedure / approach",
    frenchExample: "Il faut suivre la bonne démarche pour obtenir un visa.",
    englishExampleTranslation: "You need to follow the right process to get a visa.",
    cefrLevel: "B2",
    topicType: "ADMINISTRATION",
    examType: "ALL_EXAMS",
    frequencyScore: 90,
    tags: ["immigration", "formal"],
    isPublished: true,
    status: "NEW",
    reviewCount: 0,
  },
  {
    id: "voc_006",
    frenchWord: "davantage",
    englishMeaning: "more / further",
    frenchExample: "Nous devons travailler davantage pour réussir l'examen.",
    englishExampleTranslation: "We need to work more to pass the exam.",
    cefrLevel: "B1_PLUS",
    topicType: "EDUCATION",
    examType: "ALL_EXAMS",
    frequencyScore: 82,
    tags: ["quantity", "formal"],
    isPublished: true,
    status: "WEAK",
    reviewCount: 2,
  },
  {
    id: "voc_007",
    frenchWord: "malgré",
    englishMeaning: "despite / in spite of",
    frenchExample: "Malgré la pluie, nous sommes allés au parc.",
    englishExampleTranslation: "Despite the rain, we went to the park.",
    cefrLevel: "B1",
    topicType: "DAILY_LIFE",
    examType: "ALL_EXAMS",
    frequencyScore: 94,
    tags: ["connector", "contrast", "preposition"],
    isPublished: true,
    status: "MASTERED",
    reviewCount: 15,
    lastReviewedAt: "2026-05-04",
  },
  {
    id: "voc_008",
    frenchWord: "auprès de",
    englishMeaning: "with / at / next to / from (an authority)",
    frenchExample: "Vous pouvez faire une demande auprès de la préfecture.",
    englishExampleTranslation: "You can submit a request to the prefecture.",
    cefrLevel: "B2",
    topicType: "ADMINISTRATION",
    examType: "TCF_CANADA",
    frequencyScore: 78,
    tags: ["preposition", "formal", "administration"],
    isPublished: true,
    status: "NEW",
    reviewCount: 0,
  },
  {
    id: "voc_009",
    frenchWord: "bénéficier",
    englishMeaning: "to benefit / to enjoy (a right)",
    frenchExample: "Les résidents peuvent bénéficier d'une aide financière.",
    englishExampleTranslation: "Residents can benefit from financial assistance.",
    cefrLevel: "B2",
    topicType: "IMMIGRATION",
    examType: "ALL_EXAMS",
    frequencyScore: 86,
    tags: ["verb", "formal", "administration"],
    isPublished: true,
    status: "LEARNING",
    reviewCount: 5,
  },
  {
    id: "voc_010",
    frenchWord: "cependant",
    englishMeaning: "however / yet / nevertheless",
    frenchExample: "Il fait beau. Cependant, il fait très froid.",
    englishExampleTranslation: "The weather is nice. However, it is very cold.",
    cefrLevel: "B1_PLUS",
    topicType: "DAILY_LIFE",
    examType: "ALL_EXAMS",
    frequencyScore: 93,
    tags: ["connector", "contrast", "trap-word"],
    trapType: "CONTRAST_MARKER",
    isPublished: true,
    status: "MASTERED",
    reviewCount: 18,
    lastReviewedAt: "2026-05-04",
  },
  {
    id: "voc_011",
    frenchWord: "à condition que",
    englishMeaning: "provided that / on condition that",
    frenchExample: "Je viendrai à condition que tu me préviennes à l'avance.",
    englishExampleTranslation: "I will come provided that you let me know in advance.",
    cefrLevel: "B2",
    topicType: "OPINION",
    examType: "TEF_CANADA",
    frequencyScore: 75,
    tags: ["connector", "subjunctive", "condition"],
    isPublished: true,
    status: "WEAK",
    reviewCount: 1,
  },
  {
    id: "voc_012",
    frenchWord: "un logement",
    englishMeaning: "housing / accommodation",
    frenchExample: "Trouver un logement abordable est difficile en ville.",
    englishExampleTranslation: "Finding affordable housing is difficult in the city.",
    cefrLevel: "B1",
    topicType: "HOUSING",
    examType: "ALL_EXAMS",
    frequencyScore: 91,
    tags: ["noun", "housing", "immigration"],
    isPublished: true,
    status: "MASTERED",
    reviewCount: 10,
    lastReviewedAt: "2026-05-02",
  },
];

export const mockUserWordBank: UserWordBankItem[] = [
  {
    id: "uwb_001",
    userId: "usr_001",
    wordId: "voc_001",
    status: "LEARNING",
    easeScore: 2.6,
    reviewCount: 4,
    mistakeCount: 1,
    correctCount: 3,
    isInWeakWords: false,
    isMastered: false,
    lastReviewedAt: "2026-05-03",
    nextReviewAt: "2026-05-06",
  },
  {
    id: "uwb_002",
    userId: "usr_001",
    wordId: "voc_003",
    status: "MASTERED",
    easeScore: 3.4,
    reviewCount: 12,
    mistakeCount: 1,
    correctCount: 11,
    isInWeakWords: false,
    isMastered: true,
    lastReviewedAt: "2026-05-03",
    nextReviewAt: "2026-05-10",
  },
  {
    id: "uwb_003",
    userId: "usr_001",
    wordId: "voc_006",
    status: "WEAK",
    easeScore: 1.9,
    reviewCount: 2,
    mistakeCount: 2,
    correctCount: 0,
    isInWeakWords: true,
    isMastered: false,
    lastReviewedAt: "2026-05-02",
    nextReviewAt: "2026-05-05",
  },
  {
    id: "uwb_004",
    userId: "usr_001",
    wordId: "voc_008",
    status: "NEW",
    easeScore: 2.5,
    reviewCount: 0,
    mistakeCount: 0,
    correctCount: 0,
    isInWeakWords: false,
    isMastered: false,
  },
];
