/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import { BookOpen, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";

type Row = { id: string; french_word: string; english_meaning: string; cefr_level: string; topic: string; broad_category: string };
const levels = ["ALL", "A0", "A1", "A2", "B1", "B2", "C1"];

export function VocabularyLibraryClient() {
  const [rows, setRows] = useState<Row[]>([]); const [search, setSearch] = useState(""); const [topic, setTopic] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [level, setLevel] = useState("ALL"); const [category, setCategory] = useState("ALL"); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); const q = new URLSearchParams({ page: String(page), search, topic, level, category }); fetch(`/api/vocabulary?${q}`).then((response) => response.json()).then((payload) => { setRows(payload.rows ?? []); setTotal(payload.total ?? 0); }).finally(() => setLoading(false)); }, [page, search, topic, level, category]);
  const update = (fn: () => void) => { setPage(1); fn(); };
  return <div className="motion-enter space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="theme-soft text-xs font-black uppercase tracking-[.18em]">The FrancScore library</p><h1 className="page-title mt-2">Find your<br /><span className="editorial-title text-[var(--accent-primary)]">next word.</span></h1></div><Link href="/flashcards" className="btn btn-primary"><BookOpen className="h-4 w-4" />Study this library</Link></div>
    <section className="ui-surface p-4 sm:p-5"><div className="relative"><Search className="theme-soft absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" /><input className="input pl-12" value={search} onChange={(event) => update(() => setSearch(event.target.value))} placeholder="Search French or English" aria-label="Search vocabulary" /></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{levels.map((value) => <button key={value} onClick={() => update(() => setLevel(value))} className={`filter-chip ${level === value ? "is-selected" : ""}`}>{value === "ALL" ? "All levels" : value}</button>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="theme-muted text-xs font-black">Theme<input className="input mt-1" value={topic} onChange={(event) => update(() => setTopic(event.target.value))} placeholder="e.g. Connecting words" /></label><label className="theme-muted text-xs font-black">Broad category<select className="input mt-1" value={category} onChange={(event) => update(() => setCategory(event.target.value))}><option value="ALL">All categories</option>{["People and Family", "Food and Drink", "Home", "Travel and Transport", "Work and Education", "Health and Body", "Technology", "Grammar and Connectors", "Other"].map((value) => <option key={value}>{value}</option>)}</select></label></div></section>
    <div className="flex items-center justify-between"><p className="theme-muted text-sm font-bold">{total.toLocaleString()} matching words</p><span className="theme-soft flex items-center gap-1 text-xs font-black"><SlidersHorizontal className="h-4 w-4" /> page {page}</span></div>
    {loading ? <div className="grid gap-3 sm:grid-cols-2"><div className="ui-card skeleton-card h-40" /><div className="ui-card skeleton-card h-40" /></div> : rows.length ? <div className="motion-stagger grid gap-3 sm:grid-cols-2">{rows.map((row) => <article key={row.id} className="ui-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-black tracking-tight">{row.french_word}</h2><p className="theme-muted mt-1 text-sm">{row.english_meaning}</p></div><span className={`level-chip level-${row.cefr_level.toLowerCase()}`}>{row.cefr_level}</span></div><div className="mt-6 flex flex-wrap gap-2"><span className="theme-soft rounded-full bg-[var(--surface-muted)] px-2.5 py-1 text-xs font-bold">{row.topic}</span><span className="rounded-full bg-[var(--accent-soft)] px-2.5 py-1 text-xs font-black text-[var(--accent-primary)]">{row.broad_category}</span></div></article>)}</div> : <div className="ui-surface p-10 text-center"><Search className="mx-auto h-8 w-8 text-[var(--accent-primary)]" /><h2 className="mt-4 text-xl font-black">No words found</h2><p className="theme-muted mt-2 text-sm">Try a broader theme or reset your filters.</p><button className="btn btn-secondary mt-5" onClick={() => { setSearch(""); setTopic(""); setLevel("ALL"); setCategory("ALL"); }}>Reset filters</button></div>}
    <div className="flex items-center justify-between"><button className="btn btn-secondary" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="btn btn-secondary" disabled={page * 50 >= total} onClick={() => setPage((value) => value + 1)}>Next</button></div>
  </div>;
}
