"use client";

import { Check, Download, Moon, RotateCcw, Sun, Upload, WandSparkles } from "lucide-react";
import { useState } from "react";
import { GUEST_PROGRESS_KEY } from "@/lib/guest-progress";
import { useTheme } from "@/components/theme/ThemeProvider";

export default function SettingsPage() {
  const { choice, setTheme } = useTheme();
  const [message, setMessage] = useState("");
  const exportProgress = () => { const raw = localStorage.getItem(GUEST_PROGRESS_KEY) ?? "{}"; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([raw], { type: "application/json" })); link.download = "francscore-progress.json"; link.click(); setMessage("Progress exported."); };
  return <div className="motion-enter mx-auto max-w-2xl space-y-6"><div><p className="theme-soft text-xs font-black uppercase tracking-[.18em]">Your study space</p><h1 className="page-title mt-2">Settings</h1><p className="theme-muted mt-3 max-w-md text-sm leading-6">Make FrancScore fit the way you learn. Everything stays on this device until you choose to export it.</p></div>
    <SettingGroup title="Appearance" icon={Sun}><div className="setting-choice-grid">{(["light", "dark", "system"] as const).map((value) => <button key={value} onClick={() => setTheme(value)} className={`setting-choice ${choice === value ? "is-selected" : ""}`}><span className="setting-choice-icon">{value === "dark" ? <Moon className="h-5 w-5" /> : value === "light" ? <Sun className="h-5 w-5" /> : <WandSparkles className="h-5 w-5" />}</span><span>{value[0].toUpperCase() + value.slice(1)}</span>{choice === value ? <Check className="ml-auto h-4 w-4" /> : null}</button>)}</div></SettingGroup>
    <SettingGroup title="Learning" icon={WandSparkles}><div className="setting-row"><div><p className="font-black">Swipe controls</p><p className="theme-soft mt-1 text-sm">Use gestures while reviewing cards.</p></div><span className="status-pill status-on">Enabled</span></div><button className="setting-row w-full text-left" onClick={() => setMessage("Gesture tutorial is available from the info button on Flashcards.")}><div><p className="font-black">Gesture tutorial</p><p className="theme-soft mt-1 text-sm">Review the swipe legend anytime.</p></div><span className="theme-soft">→</span></button></SettingGroup>
    <SettingGroup title="Progress" icon={Download}><button className="setting-row w-full text-left" onClick={exportProgress}><div><p className="font-black">Export progress</p><p className="theme-soft mt-1 text-sm">Save a portable JSON backup.</p></div><Download className="theme-soft h-5 w-5" /></button><label className="setting-row w-full cursor-pointer"><div><p className="font-black">Import progress</p><p className="theme-soft mt-1 text-sm">Restore a previous backup.</p></div><Upload className="theme-soft h-5 w-5" /><input className="hidden" type="file" accept="application/json" onChange={async (event) => { const file = event.target.files?.[0]; if (file) { localStorage.setItem(GUEST_PROGRESS_KEY, await file.text()); setMessage("Progress imported."); } }} /></label><button className="setting-row danger-row w-full text-left" onClick={() => { if (confirm("Reset all guest progress?")) { localStorage.removeItem(GUEST_PROGRESS_KEY); setMessage("Progress reset."); } }}><div><p className="font-black">Reset progress</p><p className="theme-soft mt-1 text-sm">Clear review history from this device.</p></div><RotateCcw className="h-5 w-5" /></button>{message ? <p aria-live="polite" className="status-message"><Check className="h-4 w-4" />{message}</p> : null}</SettingGroup>
    <section className="ui-surface flex items-center gap-4 p-5"><div className="brand-orb">F</div><div><p className="font-black">FrancScore</p><p className="theme-soft mt-1 text-sm">A focused vocabulary studio · v2.0</p></div></section>
  </div>;
}
function SettingGroup({ title, icon: Icon, children }: { title: string; icon: typeof Sun; children: React.ReactNode }) { return <section className="ui-surface overflow-hidden"><div className="setting-group-title"><Icon className="h-4 w-4 text-[var(--accent-primary)]" />{title}</div><div className="p-3">{children}</div></section>; }
