import type { AdminResourceConfig } from "@/lib/admin/types";

const EXAM_SCOPE_OPTIONS = [
  { label: "TEF Canada", value: "TEF_CANADA" },
  { label: "TCF Canada", value: "TCF_CANADA" },
  { label: "Mixed", value: "MIXED" },
  { label: "Both", value: "BOTH" },
];

const EXAM_OPTIONS = EXAM_SCOPE_OPTIONS.filter((option) => option.value !== "BOTH");
const LEVEL_OPTIONS = [
  "A1",
  "A2",
  "B1_MINUS",
  "B1",
  "B1_PLUS",
  "B2_MINUS",
  "B2",
  "B2_PLUS",
  "C1",
].map((value) => ({ label: value, value }));
const TOPIC_OPTIONS = [
  "WORK",
  "HOUSING",
  "HEALTH",
  "ADMINISTRATION",
  "OPINION",
  "EDUCATION",
  "IMMIGRATION",
  "DAILY_LIFE",
  "ENVIRONMENT",
  "TECHNOLOGY",
  "CULTURE",
  "TRAVEL",
].map((value) => ({ label: value.replaceAll("_", " "), value }));
const SKILL_OPTIONS = [
  "LISTENING",
  "READING",
  "WRITING",
  "SPEAKING",
  "VOCABULARY",
].map((value) => ({ label: value, value }));
const DIFFICULTY_OPTIONS = ["EASY", "MEDIUM", "HARD"].map((value) => ({ label: value, value }));
const TRAP_OPTIONS = [
  "NEGATION",
  "NUMBER_DATE",
  "CONTRAST_MARKER",
  "SYNONYM_TRAP",
  "FALSE_FRIEND",
  "DOUBLE_NEGATIVE",
  "IMPLICIT_MEANING",
].map((value) => ({ label: value.replaceAll("_", " "), value }));

export const ADMIN_RESOURCE_CONFIGS: Record<string, AdminResourceConfig> = {
  passages: {
    resource: "passages",
    title: "Reading Passages",
    description: "Manage published and draft reading passages.",
    singularLabel: "Passage",
    columns: [
      { key: "title", label: "Title" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "topic", label: "Topic" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "textarea", required: true },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "word_count", label: "Word Count", type: "number" },
      { name: "estimated_minutes", label: "Estimated Minutes", type: "number" },
      { name: "highlighted_vocabulary", label: "Highlighted Vocabulary", type: "tags" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  listening: {
    resource: "listening",
    title: "Listening Audio",
    description: "Manage listening question metadata and audio URLs.",
    singularLabel: "Listening Item",
    columns: [
      { key: "question_text", label: "Question" },
      { key: "audio_url", label: "Audio URL" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
      { name: "trap_type", label: "Trap", options: [{ label: "All", value: "" }, ...TRAP_OPTIONS] },
    ],
    fields: [
      { name: "question_text", label: "Question Text", type: "textarea", required: true },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "trap_type", label: "Trap Type", type: "select", options: TRAP_OPTIONS },
      { name: "difficulty", label: "Difficulty", type: "select", options: DIFFICULTY_OPTIONS, required: true },
      { name: "option_a", label: "Option A", type: "text", required: true },
      { name: "option_b", label: "Option B", type: "text", required: true },
      { name: "option_c", label: "Option C", type: "text", required: true },
      { name: "option_d", label: "Option D", type: "text", required: true },
      { name: "correct_option", label: "Correct Option (0-3)", type: "number", required: true },
      { name: "explanation", label: "Explanation", type: "textarea", required: true },
      { name: "audio_url", label: "Audio URL", type: "text" },
      { name: "transcript", label: "Transcript", type: "textarea" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  questions: {
    resource: "questions",
    title: "Questions",
    description: "Manage reading and listening questions.",
    singularLabel: "Question",
    columns: [
      { key: "question_text", label: "Question" },
      { key: "skill_type", label: "Skill" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "skill_type", label: "Skill", options: [{ label: "All", value: "" }, ...SKILL_OPTIONS] },
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
    ],
    fields: [
      { name: "question_text", label: "Question Text", type: "textarea", required: true },
      { name: "skill_type", label: "Skill", type: "select", options: SKILL_OPTIONS, required: true },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "trap_type", label: "Trap Type", type: "select", options: TRAP_OPTIONS },
      { name: "difficulty", label: "Difficulty", type: "select", options: DIFFICULTY_OPTIONS, required: true },
      { name: "option_a", label: "Option A", type: "text", required: true },
      { name: "option_b", label: "Option B", type: "text", required: true },
      { name: "option_c", label: "Option C", type: "text", required: true },
      { name: "option_d", label: "Option D", type: "text", required: true },
      { name: "correct_option", label: "Correct Option (0-3)", type: "number", required: true },
      { name: "explanation", label: "Explanation", type: "textarea", required: true },
      { name: "passage_id", label: "Passage ID", type: "text" },
      { name: "audio_url", label: "Audio URL", type: "text" },
      { name: "transcript", label: "Transcript", type: "textarea" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  vocabulary: {
    resource: "vocabulary",
    title: "Vocabulary Words",
    description: "Manage vocabulary flashcards and examples.",
    singularLabel: "Vocabulary Word",
    columns: [
      { key: "french_word", label: "French Word" },
      { key: "english_meaning", label: "Meaning" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
    ],
    fields: [
      { name: "french_word", label: "French Word", type: "text", required: true },
      { name: "english_meaning", label: "English Meaning", type: "text", required: true },
      { name: "french_example", label: "French Example", type: "textarea" },
      { name: "english_example_translation", label: "English Translation", type: "textarea" },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "frequency_score", label: "Frequency Score", type: "number" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  "writing-prompts": {
    resource: "writing-prompts",
    title: "Writing Prompts",
    description: "Manage writing prompt content.",
    singularLabel: "Writing Prompt",
    columns: [
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "prompt", label: "Prompt", type: "textarea", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["FORMAL_LETTER", "ESSAY", "EMAIL", "REPORT", "OPINION"].map((value) => ({ label: value, value })),
        required: true,
      },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "word_limit_min", label: "Word Limit Min", type: "number" },
      { name: "word_limit_max", label: "Word Limit Max", type: "number" },
      { name: "criteria", label: "Criteria", type: "tags" },
      { name: "sample_response", label: "Sample Response", type: "textarea" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  "speaking-prompts": {
    resource: "speaking-prompts",
    title: "Speaking Prompts",
    description: "Manage speaking prompt content.",
    singularLabel: "Speaking Prompt",
    columns: [
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "cefr_level", label: "Level" },
      { key: "exam_type", label: "Exam" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "prompt", label: "Prompt", type: "textarea", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["MONOLOGUE", "DIALOGUE", "DESCRIPTION", "OPINION", "DEBATE"].map((value) => ({ label: value, value })),
        required: true,
      },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "topic", label: "Topic", type: "select", options: TOPIC_OPTIONS },
      { name: "duration_seconds", label: "Duration Seconds", type: "number" },
      { name: "preparation_seconds", label: "Preparation Seconds", type: "number" },
      { name: "criteria", label: "Criteria", type: "tags" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  badges: {
    resource: "badges",
    title: "Badges",
    description: "Manage badge unlock content.",
    singularLabel: "Badge",
    columns: [
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "xp_reward", label: "XP" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      {
        name: "category",
        label: "Category",
        options: [
          { label: "All", value: "" },
          ...["LISTENING", "READING", "WRITING", "SPEAKING", "VOCABULARY", "MOCK_TEST", "STREAK", "MASTERY"].map((value) => ({
            label: value.replaceAll("_", " "),
            value,
          })),
        ],
      },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "icon", label: "Icon", type: "text" },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["LISTENING", "READING", "WRITING", "SPEAKING", "VOCABULARY", "MOCK_TEST", "STREAK", "MASTERY"].map((value) => ({
          label: value.replaceAll("_", " "),
          value,
        })),
        required: true,
      },
      { name: "requirement", label: "Requirement", type: "textarea" },
      { name: "xp_reward", label: "XP Reward", type: "number" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  "mock-tests": {
    resource: "mock-tests",
    title: "Mock Tests",
    description: "Manage mock test sets and sections.",
    singularLabel: "Mock Test",
    columns: [
      { key: "title", label: "Title" },
      { key: "exam_type", label: "Exam" },
      { key: "section_count", label: "Sections" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_OPTIONS] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_OPTIONS, required: true },
      {
        name: "sections",
        label: "Sections JSON",
        type: "textarea",
        description:
          'Example: [{"skill_type":"LISTENING","sort_order":0,"question_count":20,"duration_minutes":25,"metadata":{}}]',
      },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  missions: {
    resource: "missions",
    title: "Daily Missions",
    description: "Publish real War Mode missions backed by user activity.",
    singularLabel: "Mission",
    columns: [
      { key: "title", label: "Title" },
      { key: "task_type", label: "Task" },
      { key: "target_count", label: "Target" },
      { key: "xp_reward", label: "XP" },
      { key: "is_published", label: "Published" },
    ],
    filters: [
      { name: "skill_type", label: "Skill", options: [{ label: "All", value: "" }, ...SKILL_OPTIONS] },
      { name: "exam_type", label: "Exam", options: [{ label: "All", value: "" }, ...EXAM_SCOPE_OPTIONS] },
      { name: "cefr_level", label: "Level", options: [{ label: "All", value: "" }, ...LEVEL_OPTIONS] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "skill_type", label: "Skill", type: "select", options: SKILL_OPTIONS, required: true },
      {
        name: "task_type",
        label: "Task Type",
        type: "select",
        options: ["flashcards", "listening", "reading", "writing", "speaking", "weakness_quest"].map((value) => ({
          label: value.replaceAll("_", " "),
          value,
        })),
        required: true,
      },
      { name: "exam_type", label: "Exam Type", type: "select", options: EXAM_SCOPE_OPTIONS, required: true },
      { name: "cefr_level", label: "CEFR Level", type: "select", options: LEVEL_OPTIONS, required: true },
      { name: "target_count", label: "Target Count", type: "number" },
      { name: "xp_reward", label: "XP Reward", type: "number" },
      { name: "estimated_minutes", label: "Estimated Minutes", type: "number" },
      { name: "icon", label: "Icon", type: "text" },
      { name: "content_ref_type", label: "Content Ref Type", type: "text" },
      { name: "content_ref_id", label: "Content Ref ID", type: "text" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
};
